INSERT INTO categories (name, slug) VALUES
    ('Electronics', 'electronics'),
    ('Books', 'books'),
    ('Home & Kitchen', 'home-kitchen'),
    ('Fashion', 'fashion'),
    ('Sports & Outdoors', 'sports-outdoors'),
    ('Beauty & Personal Care', 'beauty');

INSERT INTO products (name, description, price, stock, image_url, active, category_id) VALUES
    ('Wireless Earbuds Pro', 'Bluetooth 5.3 earbuds with active noise cancellation and 30-hour battery.', 4999.00, 120, 'https://picsum.photos/seed/wireless-earbuds-pro/600/400', TRUE, (SELECT id FROM categories WHERE slug = 'electronics')),
    ('Smartwatch Fit 2', 'AMOLED fitness smartwatch with heart-rate and SpO2 tracking.', 7499.00, 80, 'https://picsum.photos/seed/smartwatch-fit-2/600/400', TRUE, (SELECT id FROM categories WHERE slug = 'electronics')),
    ('Mechanical Keyboard TKL', 'Tenkeyless mechanical keyboard with hot-swappable brown switches.', 5499.00, 45, 'https://picsum.photos/seed/mechanical-keyboard-tkl/600/400', TRUE, (SELECT id FROM categories WHERE slug = 'electronics')),
    ('USB-C Power Bank 20000mAh', 'Fast-charging 20000mAh power bank with 22.5W PD output.', 1899.00, 200, 'https://picsum.photos/seed/usb-c-power-bank-20000mah/600/400', TRUE, (SELECT id FROM categories WHERE slug = 'electronics')),
    ('4K Action Camera', 'Waterproof 4K60 action camera with image stabilisation.', 12999.00, 25, 'https://picsum.photos/seed/4k-action-camera/600/400', TRUE, (SELECT id FROM categories WHERE slug = 'electronics')),
    ('Portable Bluetooth Speaker', 'IPX7 waterproof speaker with deep bass and 12-hour playtime.', 2799.00, 150, 'https://picsum.photos/seed/portable-bluetooth-speaker/600/400', TRUE, (SELECT id FROM categories WHERE slug = 'electronics')),
    ('The Pragmatic Programmer', 'Classic guide to software craftsmanship, 20th anniversary edition.', 899.00, 60, 'https://picsum.photos/seed/the-pragmatic-programmer/600/400', TRUE, (SELECT id FROM categories WHERE slug = 'books')),
    ('Clean Architecture', 'Robert C. Martin on software structure and design.', 749.00, 40, 'https://picsum.photos/seed/clean-architecture/600/400', TRUE, (SELECT id FROM categories WHERE slug = 'books')),
    ('Designing Data-Intensive Applications', 'Martin Kleppmann on reliable, scalable, maintainable systems.', 1299.00, 35, 'https://picsum.photos/seed/designing-data-intensive-applications/600/400', TRUE, (SELECT id FROM categories WHERE slug = 'books')),
    ('Atomic Habits', 'James Clear on building good habits and breaking bad ones.', 499.00, 300, 'https://picsum.photos/seed/atomic-habits/600/400', TRUE, (SELECT id FROM categories WHERE slug = 'books')),
    ('Sapiens', 'A brief history of humankind by Yuval Noah Harari.', 599.00, 90, 'https://picsum.photos/seed/sapiens/600/400', TRUE, (SELECT id FROM categories WHERE slug = 'books')),
    ('Stainless Steel Pressure Cooker 5L', 'Induction-compatible 5-litre pressure cooker.', 2299.00, 70, 'https://picsum.photos/seed/stainless-steel-pressure-cooker-5l/600/400', TRUE, (SELECT id FROM categories WHERE slug = 'home-kitchen')),
    ('Non-Stick Tawa 28cm', 'Granite-coated non-stick tawa for dosas and rotis.', 899.00, 110, 'https://picsum.photos/seed/non-stick-tawa-28cm/600/400', TRUE, (SELECT id FROM categories WHERE slug = 'home-kitchen')),
    ('Electric Kettle 1.5L', '1500W stainless steel kettle with auto shut-off.', 1199.00, 130, 'https://picsum.photos/seed/electric-kettle-1-5l/600/400', TRUE, (SELECT id FROM categories WHERE slug = 'home-kitchen')),
    ('Cotton Bedsheet Set', 'Queen-size 210 TC cotton bedsheet with two pillow covers.', 1499.00, 55, 'https://picsum.photos/seed/cotton-bedsheet-set/600/400', TRUE, (SELECT id FROM categories WHERE slug = 'home-kitchen')),
    ('Mixer Grinder 750W', 'Three-jar 750W mixer grinder for wet and dry grinding.', 3499.00, 40, 'https://picsum.photos/seed/mixer-grinder-750w/600/400', TRUE, (SELECT id FROM categories WHERE slug = 'home-kitchen')),
    ('Mens Linen Shirt', 'Breathable regular-fit linen shirt.', 1599.00, 100, 'https://picsum.photos/seed/mens-linen-shirt/600/400', TRUE, (SELECT id FROM categories WHERE slug = 'fashion')),
    ('Womens Kurta Set', 'Printed cotton kurta with palazzo pants.', 1899.00, 85, 'https://picsum.photos/seed/womens-kurta-set/600/400', TRUE, (SELECT id FROM categories WHERE slug = 'fashion')),
    ('Running Sneakers', 'Lightweight mesh running shoes with cushioned sole.', 2999.00, 65, 'https://picsum.photos/seed/running-sneakers/600/400', TRUE, (SELECT id FROM categories WHERE slug = 'fashion')),
    ('Leather Wallet', 'Genuine leather bi-fold wallet with RFID protection.', 799.00, 140, 'https://picsum.photos/seed/leather-wallet/600/400', TRUE, (SELECT id FROM categories WHERE slug = 'fashion')),
    ('Aviator Sunglasses', 'UV400 polarised aviator sunglasses.', 1299.00, 75, 'https://picsum.photos/seed/aviator-sunglasses/600/400', TRUE, (SELECT id FROM categories WHERE slug = 'fashion')),
    ('Yoga Mat 6mm', 'Anti-slip TPE yoga mat with carry strap.', 899.00, 160, 'https://picsum.photos/seed/yoga-mat-6mm/600/400', TRUE, (SELECT id FROM categories WHERE slug = 'sports-outdoors')),
    ('Adjustable Dumbbell Set 20kg', 'Pair of adjustable dumbbells with spinlock collars.', 3999.00, 30, 'https://picsum.photos/seed/adjustable-dumbbell-set-20kg/600/400', TRUE, (SELECT id FROM categories WHERE slug = 'sports-outdoors')),
    ('Cricket Bat Kashmir Willow', 'Full-size Kashmir willow bat for leather ball.', 2499.00, 50, 'https://picsum.photos/seed/cricket-bat-kashmir-willow/600/400', TRUE, (SELECT id FROM categories WHERE slug = 'sports-outdoors')),
    ('Cycling Helmet', 'Ventilated lightweight helmet with adjustable fit.', 1799.00, 45, 'https://picsum.photos/seed/cycling-helmet/600/400', TRUE, (SELECT id FROM categories WHERE slug = 'sports-outdoors')),
    ('Insulated Water Bottle 1L', 'Double-wall stainless steel bottle, keeps cold for 24 hours.', 699.00, 250, 'https://picsum.photos/seed/insulated-water-bottle-1l/600/400', TRUE, (SELECT id FROM categories WHERE slug = 'sports-outdoors')),
    ('Vitamin C Face Serum', '10 percent vitamin C serum for brighter skin, 30ml.', 599.00, 180, 'https://picsum.photos/seed/vitamin-c-face-serum/600/400', TRUE, (SELECT id FROM categories WHERE slug = 'beauty')),
    ('Herbal Shampoo 400ml', 'Sulphate-free shampoo with amla and bhringraj.', 349.00, 220, 'https://picsum.photos/seed/herbal-shampoo-400ml/600/400', TRUE, (SELECT id FROM categories WHERE slug = 'beauty')),
    ('Sunscreen SPF 50', 'Lightweight broad-spectrum sunscreen, 50g.', 449.00, 190, 'https://picsum.photos/seed/sunscreen-spf-50/600/400', TRUE, (SELECT id FROM categories WHERE slug = 'beauty')),
    ('Beard Trimmer', 'Cordless trimmer with 20 length settings.', 1699.00, 60, 'https://picsum.photos/seed/beard-trimmer/600/400', TRUE, (SELECT id FROM categories WHERE slug = 'beauty'));
